context:
  version: 6.18.0

package:
  name: babylon
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/babylon/-/babylon-${{ version }}.tgz
  sha256: ce1e81d36b5789279f8aba716d2ec5aabecbc306585f867f1a6a1c8dc478d88c

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - babylon

about:
  license: MIT
  license_file: LICENSE
  summary: "output coverage reports using Node.js' built in coverage"
  homepage: https://github.com/bcoe/babylon
  repository: https://github.com/bcoe/babylon

extra:
  recipe-maintainers:
    - danielnachun
